spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://localhost:8888
  autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration