server:
  port: 8070
spring:
  application:
    name: msvc-branch
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecomarketdtbs
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    sql:
      init:
        mode: always
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka